### ISSUE TITLE
Resolved entrypoint (-e) based on selected package (-p)

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#1007]
The current behavior of `migrate -p -packages/addons/super-addon -e src` will throw:

```
Could not find entrypoint /project/addon. Please make sure it is existed and inside your project(/project).
 ```
 
The expected behavior is `-e` to be resolved based on selected package `-p` (entrypoint to be = `/project/packages/addons/super-addon/addon` instead of `/project/addon`).

The same behavior expected to be implemented in all commands (graph, move, fix)

**Comment by egorio** [comment]
Please, consider next:

- `Fix` do not depend on existing js files (no more: " TS conversion task, no JS files detected")
- If no files are found, include the path in the error message, like `Error "No files found in [path]` instead of `TS conversion task, no JS files detected`
- Resolve -e based on -p (https://github.com/rehearsal-js/rehearsal-js/issues/1007).

**Comment by lynchbomb** [comment]
instead of having entrypoint lets just resolve the package as the entrypoint (essentially package is entrypoint)

**Comment by egorio** [comment]
Close the ticket in favor of [--source](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/commands/move/index.ts#L39-L48) param.
