### ISSUE TITLE
Add graphviz support to `graph`

### ISSUE THREAD

**Issue by chadhietala** [rehearsal-js/rehearsal-js#1026]
We should add dot lang support to `graph` as an output format so that people can visualize the graph.

Something like:

```
rehearsal graph  --format dot -o graph.dot
```

**Comment by egorio** [comment]
Cool idea. One of the formatters can be HTML like this https://observablehq.com/@d3/tree

**Comment by chadhietala** [comment]
@wondersloth yea I was using that to debug and found to be handy.
