### ISSUE TITLE
Better way to check required dependencies 

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#1052]
We currently searching for required dependencies in the root package.json, but they can be installed only in the target package's package.json only.

We need to better check for required deps... either, 
- check all package.json files from the package dir to the root dir
- or just do something like using the execa

Refs:
- https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/utils/src/cli.ts#L678
- https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/service/src/glint-utils.ts#L17

**Comment by lynchbomb** [comment]
We can just expand this to include the package directory https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/utils/prereq-checks.ts#L166 remove duplicates and then verify

**Comment by egorio** [comment]
Can be fixed by using https://github.com/typed-ember/glint/issues/579

**Comment by egorio** [comment]
Close
