### ISSUE TITLE
rehearsal todo absolute paths in comments

### ISSUE THREAD

**Issue by lynchbomb** [rehearsal-js/rehearsal-js#1085]
The @rehearsal TODO is adding a comment to a missing type with an absolute path. This should instead inline a comment with a relative path starting at `rootPath`. 

### BUG CURRENT EXAMPLE

// @ts-expect-error @rehearsal TODO TS7016: Could not find a declaration file for module 'ember-asset-loader/addon/services/asset-loader'. '/Users/medwards/Code/muuto/test-packages/voyager-web/node_modules/ember-asset-loader/addon/services/asset-loader.js' implicitly has an 'any' type..   Try `npm i --save-dev @types/ember-asset-loader` if it exists or add a new declaration (.d.ts) file containing `declare module 'ember-asset-loader/addon/services/asset-loader';`

### EXPECTED

// @ts-expect-error @rehearsal TODO TS7016: Could not find a declaration file for module 'ember-asset-loader/addon/services/asset-loader'. 'voyager-web/node_modules/ember-asset-loader/addon/services/asset-loader.js' implicitly has an 'any' type..   Try `npm i --save-dev @types/ember-asset-loader` if it exists or add a new declaration (.d.ts) file containing `declare module 'ember-asset-loader/addon/services/asset-loader';

**Comment by wondersloth** [comment]
Another example is in the report. 

```
  "summary": [
    {
      "projectName": "root",
      "tsVersion": "4.9.3",
      "timestamp": "5/26/2023, 15:50:02",
      "basePath": "/Users/medwards/Code/muuto/test-packages/voyager-web/.rehearsal",
      "entrypoint": "",
      "commandName": "@rehearsal/fix"
    }
  ],
```

BasePath in report will change from user to user. So at this time it may not be advised to check in this file.

**Comment by lynchbomb** [comment]
Im going to clean the `summary` up a bit. We dont need `commandName`, `entrypoint` or `basePath` in the summary anymore.
