### ISSUE TITLE
bug: file out of scope of nearest package to srcPath; throws Could not find source file: path/to/file.ts

### ISSUE THREAD

**Issue by wondersloth** [rehearsal-js/rehearsal-js#1110]
When fixing a package in a workspace, using `--graph`

- Running `rehearsal graph packages/some-package`
- We may get files that are outside of the closes package.json boundary.

```
package/another-package/utils/is-browser.ts
package/some-package/index.js
```
- When using `rehearsal  fix --graph packages/some-package`
- Running fix will break against that srcPath

```
$ yarn rehearsal fix packages/some-addon/addon/
info:    @rehearsal/fix 3.0.7-beta
✔ Initialize
✔ Analyzing project dependency graph ...
✖ Could not find source file: '/Users/jsmith/Code/some-project/packages/another-addon/addon/utils/is-browser.ts'.
```

**Comment by lynchbomb** [comment]
Looks like this issue was flagged running against beta. We you validate the latest 1.* build hasn't resolved this?
