### ISSUE TITLE
[feat] progress & duration in the CLI

### ISSUE THREAD

**Issue by lynchbomb** [rehearsal-js/rehearsal-js#1239]
We should add a progress in the CLI and timestamp before / end for duration of execution. eg.

```
// progress
processing file: /src/get-live-neighbor-count.ts
[==============-----------------] 33% | 5/15 files | ETA: 17 min
```

```
// duration
Duration: 15m 33s

Types Inferred
   15 errors caught by rehearsal
   6 have been fixed by rehearsal
   9 errors need to be fixed manually
     -- 4 ts errors, marked by @ts-expect-error @rehearsal TODO
     -- 5 eslint errors, with details in the report"
```

We should already have enough information to render this. We could possibly timestamp before after each file and update the ETA based on the average diff. eg.

Duration to process the first file is 77 seconds. Total files is 15.
77s * 15f = 1155s ETA

Duration to process the second file is 33 seconds. Update the formula based on the average of 77s + 33s. Updated ETA per file is 55 seconds etc. etc.

**Comment by egorio** [comment]
I also liked the idea of having a files tree with checkmarks like this, but could be done as another improvement for the progress bar in the future:

![image](https://github.com/rehearsal-js/rehearsal-js/assets/1502496/24559a73-9652-4960-aa75-5f7291e654f0)

**Comment by lynchbomb** [comment]
@egorio yeah totally. we could combine the two and implement in iteration. low-hanging fruit first.
