### ISSUE TITLE
Reporter Format

### ISSUE THREAD

**Issue by lynchbomb** [rehearsal-js/rehearsal-js#206]
Currently the generated report only supports terminal output and JSON. Tracking an issue to expand the format eg. HTML, Markdown, SARIF. Additionally leveraging tools such as [CheckupJS](https://checkupjs.github.io/).

Additionally adding source-map links to IDE if possible (to show LOE).

We should include a detailed breakage report similar to:
https://github.com/microsoft/TypeScript/issues/49835

As we already have most of this data already, just a matter of formatting. The typescriptlang playground links can be the input/output of the transform test files.

**Comment by egorio** [comment]
Seems done
