### ISSUE TITLE
Latest tsc version check beta | latest

### ISSUE THREAD

**Issue by lynchbomb** [rehearsal-js/rehearsal-js#242]
Cover instances when the current `latest` release is newer than the `beta` release

**Comment by egorio** [comment]
It's not clear which tag should be used by rehearsal by default, for example, today:
```
@beta  = 4.8.0-beta
@dev    = 3.9.4
@latest  = 4.8.3
@next    = 4.9.0-dev
@rc      = 4.8.1-rc
```
while the list of available versions (`yarn info typescript versions`) looks like this:
```
  '4.7.4',
  '4.8.0-beta',
  '4.8.0-dev.***',
  '4.8.1-rc',
  '4.8.2',
  '4.8.3',
  '4.9.0-dev.***'
 ```
  
This shows that non of the tagged versions can be used by Rehearsal directly - `@latest` don't include non-stable builds, `@beta` and `@rc` builds can be lower than the `@latest`, and `@dev` is too unstable to test against of (but can be used to collect errors).

The current target should be `4.8.3` (as the latest stable-ish version) which is represented by `@latest`, but when `4.9` `beta` and `rc` will be released, we have to use `@beta` or `@rc` corresponding.
  
This means we can't use TS tags directly and as a proposal to use the result of `yarn info typescript versions` to calculate the latest target version.

**Comment by chadhietala** [comment]
I believe you're going to need to actually hit the [registry endpoint](https://registry.npmjs.com/typescript) and look at the tags. You'll likely then need to constraint solve with the [semver package](https://www.npmjs.com/package/semver). Its likely that you're going to want to write the last tested version somewhere so you can compare.

**Comment by lynchbomb** [comment]
In this scenario rehearsal upgrade should fetch @latest by default since its gt @beta. As a default we should do a semver comparison of app vs @beta vs @latest
```
app     = 4.7.0
@beta   = 4.8.0-beta
@latest = 4.8.3
```


In this scenario rehearsal upgrade should exit as @beta is lt @latest and app is gt @beta
```
app     = 4.8.3
@beta   = 4.8.0-beta
@latest = 4.8.3
```

And wrt @next this should only be fetched for reporting purposes, no codemods

**Comment by egorio** [comment]
Solution: https://github.com/rehearsal-js/rehearsal-js/pull/404
