### ISSUE TITLE
Dogfood CWF Librarys

### ISSUE THREAD

**Issue by lynchbomb** [rehearsal-js/rehearsal-js#249]

**Comment by aviheidir** [comment]
Is this for dogfooding Rehearsal upgrade only? If so, it's already completed, right? If not, can we dogfood  Rehearsal migrate on JavaScript libraries in [this list](https://docs.google.com/spreadsheets/d/11PM0gBXnSgQqSam7t7wpWi6B0cH42kKee6d8p2IQpnc/edit#gid=37082440)?
