### ISSUE TITLE
Reduce a required TS version for packages

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#305]
Rehearsal is intent to be running on older version of TS and to instal latest version upon run.
Currently we require projects to be already on minimum 4.7, which doesn't make sense. 

![image](https://user-images.githubusercontent.com/1502496/186287746-5004ba8a-3064-4d37-b28a-f6348be2b7f1.png)

**Comment by lynchbomb** [comment]
Im pretty sure we can close this issue. The comment above isn't entirely correct. Rehearsal doesn't require a minimum of 4.7. eg https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/test/commands/upgrade.test.ts#L14 (typescript@4.5.5)

**Comment by egorio** [comment]
This is about https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/utils/package.json#L38.
This means the app or global installed TS has to be at least 4.7.

I think we can try to reduce peerDep to 4.0 or even lower, which means people with projects on 4.0 will be able to use rehearsal to upgrade to 4.9 without any errors in the console.
