### ISSUE TITLE
bug: Make rehearsal executable

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#306]
It seems rehearsal is not globally executable anymore (after migration o commander). 
Need to fix this.

![image](https://user-images.githubusercontent.com/1502496/186293279-70d80027-a064-4c9a-a142-4a270f8a878b.png)

**Comment by haochuan** [comment]
Yeah saw the same thing, will take a look and have a fix soon

**Comment by haochuan** [comment]
@egorio @lynchbomb Can you help verify if this still happens to you guys? I just checked again and it's working for me know. My guess is before we didn't have the right permission for `cli/bin/rehearsal.js`.

**Comment by lynchbomb** [comment]
@haochuan confirmed this is no longer an issue. @egorio run
`chmod 755 ./bin/rehearsal.js && volta install @rehearsal/cli`
