### ISSUE TITLE
Migration Notes

### ISSUE THREAD

**Issue by chadhietala** [rehearsal-js/rehearsal-js#350]
Some observations:

- Codefix in LS for JSDoc -> annotations work very well for primitive types
- Doesn't seem to handle `@typedef` annotations and likely other exotic annotations :(
   - We likely need to write something that can do this
- One can generate the declarations from JS files though
- Telling people to write good JSDocs seems like really good advice

**Comment by egorio** [comment]
https://github.com/airbnb/ts-migrate/blob/master/packages/ts-migrate-plugins/src/plugins/jsdoc.ts

**Comment by lynchbomb** [comment]
Closing this notes issue as we are tracking the bullets listed in other issues
