### ISSUE TITLE
Add reporter to migration-graph API

### ISSUE THREAD

**Issue by wondersloth** [rehearsal-js/rehearsal-js#367]
Currently migration-graph libraries are using debug only for output, migrate debug output to use reporter.

**Comment by lynchbomb** [comment]
Not sure that we need a reporter for the migration-graph-*. All reporting in this space will happen from the CLI Migrate command. The migration-graph-* should only provide proper order. State management and reporting is an implementation detail coming from @rehearsal/cli.migrate
