### ISSUE TITLE
idea: Create GitHub Issues / Jira Tickets for unresolved diagnostic codes

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#373]
We can automatically create GitHub Issues / Jira Tickets as a result of GitHub Action for errors we can't resolve automatically and we need some interaction from developer. 

In Issues / Tickets description we can provide a better suggestions with code examples to choose from

GitHub Issues can be created automatically from GitHub actions, for Jira we have to provide some API configs in GitHub Action params.

We have to track previously created issues to avoid creating copies for closed ones.

**Comment by lynchbomb** [comment]
Moving this to backlog
