### ISSUE TITLE
feat: follow fully qualified service injections for Ember apps

### ISSUE THREAD

**Issue by chadhietala** [rehearsal-js/rehearsal-js#390]
In Ember apps you can have fully qualified service injections like so:

```js
class SomeComponent extends Component {
  @service('authentication@authenticated-user') authenticatedUser;
}
```

```
'authentication@authenticated-user'
 ~~~~~~~~~~~~~~ ^^^^^^^^^^^^^^^^^^
 ~ addon name   ^service name
```

In these cases we likely want to treat this code as if it was consuming the service via an import. For example, this is what the actual TS code would look like *after* conversion:

```ts
import AuthenticatedUser from 'authentication/services/authenticated-user';

class SomeComponent extends Component {
  @service('authentication@authenticated-user')
  declare authenticatedUser: AuthenticatedUser;
}
```

This would mean that we would add the `authenticated-user service` to the graph order (instead of implying on heuristics) and it should come before `SomeComponent`. 

If we see a service injection with a non qualified injection path

```js
class SomeComponent extends Component {
  @service('tracking') tracking;
  @service('my-service') myService;
}
```

We have to follow this resolution logic:
- checking to see if it's locally defined e.g. `/app/services/*.js`
- If it is there than we need to add it to the graph as we did above.
- If it's not there its coming from some addon. 

In the case where the service is unknown likely going to want to ask where to resolve the service in interactive mode and/or provide a way to give the users a "unresolvable tokens" manifest that they can file out and re-run the migration with to resolve those identifiers.

**Comment by wondersloth** [comment]
I chatted with @chriskrycho about this today. 

I hacked out some simple heuristics based off of file path, and that definitely won't cut it given that services can be used in multiple places components, adapters, routes, services.

The current work I've done from that hack I can carry forward into addressing this feature.

**Comment by lynchbomb** [comment]
In addition to migration ordering, lets keep this issue open as we will also need to handle type inference to handle the import and declaration of the service eg:

```
>>>>> import AuthenticatedUser from 'authentication/services/authenticated-user';

class SomeComponent extends Component {
       @service('authentication@authenticated-user')
>>>>>  declare authenticatedUser: AuthenticatedUser;
}
```

**Comment by wondersloth** [comment]
@lynchbomb 

Just to clarify the additional feature request:

rehearsal should use the meta data from the migration graph to transform the resolver based calls for service decorators, from:

```
import Component from '@glimmer/component';
import { inject as service } from '@ember/service';
import { action } from '@ember/object';

export default class CartContentsComponent extends Component {
  @service('ShoppingCart') shoppingCart;

  @action
  remove(item) {
    this.shoppingCart.remove(item);
  }
}
```

to the following:

```
import Component from '@glimmer/component';
import { inject as service } from '@ember/service';
import { action } from '@ember/object';

import ShoppingCartService from 'my-app/services/shopping-cart';

export default class CartContentsComponent extends Component {
  // https://docs.ember-cli-typescript.com/ember/services
  @service declare shoppingCart: ShoppingCartService;

  // OR this...
  @service('ShoppingCart') declare shoppingCart: ShoppingCartService;

  @action
  remove(item) {
    this.shoppingCart.remove(item);
  }
}
```
Reference for output.

You'd like for us to add the `import` and `declare authenticatedUser: AuthenticatedUser;` 

Want to clarify this, before we decompose this to tasks.
