### ISSUE TITLE
bug: Couldn't find any versions for "@rehearsal/migrate" that matches "workspace:*

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#408]
Rehearsal @0.0.37 is broken with the error:

```
Couldn't find any versions for "@rehearsal/migrate" that matches "workspace:*
```

Probably: https://lerna.js.org/docs/recipes/using-pnpm-with-lerna

**Comment by lynchbomb** [comment]
Yeah before publishing the workspace alias should be transformed to regular aliased dependency automatically, my guess is either lerna or pnpm this isn't happening. If it were the above example should become: `"@rehearsal/migrate": "0.0.37"`.

I'll try and replicate the error above and unravel lerna
