### ISSUE TITLE
feat: Utilize all available TypeScript's codefixes automatically  

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#411]
TS team is adding codefixes for new features to help developers fix the code in IDEs.
We can have a plugin to codefix to utilize them automatically (all to to have some allowed list) instead of doing [this one by one](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/codefixes/src/7006/index.ts#L24-L31)

This will help to fix code in advance as soon as TS team released codefixes.

https://github.com/microsoft/TypeScript/tree/main/src/services/codefixes

**Comment by lynchbomb** [comment]
This will likely include leveraging ts jsDoc fixes for type inference
