### ISSUE TITLE
Inherited Object Types

### ISSUE THREAD

**Issue by chadhietala** [rehearsal-js/rehearsal-js#424]
Note: This should be attempted only once we feel good about library code getting transformed.

One of the challenges for migration is going to be dealing with framework specific objects. This is challenging because TypeScript offers no code action for filling in types from the super class.

[Example](https://www.typescriptlang.org/play?#code/MYGwhgzhAECCB2BLAtmE0DeAoavoTAE8AKZAUyjAHMyAufAFwCdF4qBKeiZ1qzHPIKZkGAVybxoAcgAWZECAD2UgNwDcAXyxasoSDAAiivmQAeDMvAAmMBCjT9BBEuUo12maAHov0AMKKVmRwwAyIipJywtAA7ogK0GISiTKIMKwMitAABq4ENPRg8ITZ6oLQwkmSUgBGYExSZVo6elD+YAzQZhbWtkio6NiCigBuZEwsQfhEpBT5ZB4Y3r4BU7Ch4ZHjwXEJVSlp0BlZuXPUdNBFJZcwMfIgZUIi4tV1DU3aQA)

Since methods on framework objects typically get called by the framework it self instead of other application code the signatures are actually well known and should not vary. Given this aspect I think we can get very far at emitting the correct framework types by transforming the code in 3 stages to get code actions to do much of the heavy lifting.

Stage 1:

In stage 1 we exam the code and determine if a framework object is being extended. We then look at that type and determine what what members it contains. From there we look at what the developer overrode and we build a temporary type that `Pick`s the values out of the super class type.

[Example Stage 1](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAcgKYgEZKgWgM4QK5QDGSCA3AFCiSyIrpa4HED0MAnmEts2FEgG7AkAdzKVw0eACV8MJHABmUCCEQABOhmbK8MYADsA5ttkkK5dpzhSkACyQBDKNgcAbAPpzwnjknczdeQBeOAAFYEIAawAeALkAGkR0BWgkAFkIABMkVwQ4AB9EECychAA+ckqkAA9qeEJXB2xsOAAxCAg4Grl9TJa4+QBvcjhRuGTUjOzXAAoYKAd9bGA9CH0ASjhhsZ24YAU4OYWlleA1gDoYToAya7h5xeXV-UuIc-0HECRN7d2-wjWuFcSHOrgghiOj1Oa3WFD+owAviMxkjkaNitMZmAnJ9sD80bt9odsQsQNh3p9vlsCfC4AClhBgaDwVicWTYTSUZUdkjUUA)

Stage 2:

In stage 2 we need to temporarily comment out the extension of the super class and instead have the class `implements` our temporary type. In addition to to that we need to temporarily comment out the body of the class. In doing so we will get a code action on the class that will ask us if we want to implement the interface. When we run the code action we are left with the following. Noticed that it pulled in the correct `Transition` type.

[Example Stage 2](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAcgKYgEZKgWgM4QK5QDGSCA3AFCiSyIrpa4HED0MAnmEts2FEgG7AkAdzKVw0eACV8MJHABmUCCEQABOhmbK8MYADsA5ttkkKVSXBhQAhvuzA9EfYuWqEGtFp16jrW-aOwM5i5OyccFJIABZINlDYNgA2APpy4GkcSCkyuvIAvHAACsCEANYAPLlyADSI6ArQSACyEAAmSEkIcAA+iCDtnQgAfORjSAAe1PCESTbY2HAAYhAQcMwAVJNy+m2L1UgbzHBUSShI+jD7MXEJyWkoYJmcOaZwAN7kDU2tHUkAFNY7A4nPoAFxWAIg4L6Cp4fRlfQQYT6YYASgh-AgwDaPSKbmA2CQcIRSJRww+YWiymEcH0IjgAFEoMooP8EM0kDBou06RB4KdzpckG0AHQINEUAC+5AGf3+YHiNhA2AhEFQACskIQYDUgYFQRD9dDnCTEcjURi4PDzSjKdyaXSGczWezOdzeUiBeAziALnIxRLpeQ4KH1sdvnxfp1AVCgs40ZSw+HkycFHBY8D4-pRTA1gAyfOQrOg3MQUX6ZVIROfZPMY6psOEZy4M6ipIQQyZg0wyUhsP11MyuvHGX90ODuUxxW2FU18cp5PAdMKpUqitV+cjxtNlsQNsdrsz5XYPvb5Nj7cysdAA)

Stage 3

In the third and final stage we need to merge the class body, remove the `implements` and our temp type, and then run any eslint/prittier fixes.

[Example Stage 3](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAcgKYgEZKgWgM4QK5QDGSCA3AFCiSyIrpa4HED0MAnmEts2FEgG7AkAdzKVw0eACV8MJHABmUCCEQABOhmbK8MYADsA5ttkkKVSXAAqUAIb7swPRH2LlqhBrRadeo6zsHJ2AXMXIkAA9qeEIAG1tsbDgAMQgIOEi5fQATJJldeQBvcjhSuHQFaCQAWQhspFiAChhAx2d9AC5rVuCXAB48fQBrfQhhfQA+AEou-ghgbLgAHzgABXdgbCQB4dHxibhisuO4YAU4Zp72gDoYdIAye7gW+zaQ-VuIa-1bECQpw4lE7AwguXCxJDXWIQQyXV69fRTCjA0oAXyBaIxcBAdQajTAtjsIGwXQgqAAVkhCDAADQvILtLo2eHtHYjMaTGZwQbs8aAlGnc74wm-bDfX7-fkCsqghwQCFQmHConYJFY47ojXkVFAA)

This is not perfect but it is much better for us to do something like this for well known methods rather than infering the types based on usage or emit types from JS and merging them back.

[Example of inferring based on usage](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAcgKYgEZKgWgM4QK5QDGSCA3AFCiSyIrpa4HED0MAnmEts2FEgG7AkAdzKVw0eACV8MJHABmUCCEQABOhmbK8MYADsA5ttkkK5JAA9q8QgBsAhtmxwAYhAhwrc-QBMXMrryAN7kcOFw6ArQSACyEL5IdgAUMFAO+tjAehD6AFxwwXAwEAVF+g4gSAUZbKRwAL71DQCUhWERncAKcKnpmdnAuQB0JXAAZOPF-Vk5+qMQwxVVbaGd6xGEubh2SMN2EIZ9GbND+i0UG+ENHde3cCAJSclgDukg2GVwy9Vwtc2re5dHovN6VbBLSpIQFXdZbTIQXb7Q6g97YC5AiI3To3BpAA)

[Example of JS Types](https://www.typescriptlang.org/play?filetype=js#code/JYWwDg9gTgLgBAJQgVxgUzgMyhEcDkAAmiAEZpQD0OqwAdgObUrr4DcAUB2gB6SxwAxgBsAhgGdxcAGIQIcXujoATKUlQYA3hzi645TNDQBZCMrTCAFDCii644DGAQ6ASjja9XuMExxrtvaOznQAdDDyAGSRcDZ2Dk4u4RChdKIgaO6e3jmCLuIQwmihwhAMAfHBLq6cOboAvjp6jV4gZhaWYKK2IOJZTTm+-l094qnpmR4Ddbp59oXFpeUj6X21dS3NHI0cQA)

**Comment by egorio** [comment]
@chadhietala inlay hints have correct types for a simple solution... checking more complex one :)



![Image](https://user-images.githubusercontent.com/1502496/217116378-7bc3c1bb-fac4-43e7-a065-53cde58802a1.png)
