### ISSUE TITLE
Package Manager Discovery Correctness

### ISSUE THREAD

**Issue by chadhietala** [rehearsal-js/rehearsal-js#437]
I think we may want to change how we resolve the package manager to be a bit more forgiving.

## Explanation 

If you have installed rehearsal globally on your machine and you point migrate to a directory like so:

```
rehearsal migrate -p ./some-package
```

What will end up happening is that we will start looking for files from the [`process.cwd()`](https://github.com/rehearsal-js/rehearsal-js/blob/44d8c2083bfb2d5d58c5cbb6b20850412ec3d93d/packages/cli/src/utils.ts#L148) instead of the path that is passed. This can lead to using the wrong package manager.

## Options

I think are several options here but I think what users would expect is that by default we use `process.cwd()` but if a path is passed will lookup from that path to figure out the package manager. This would make `rehearsal migrate` and `rehearsal migrate -p .` synonymous, it also means you could run it anywhere in a project and we would resolve correctly.

**Comment by chadhietala** [comment]
I think this may already be fixed from what I can tell.

**Comment by brendaHuang** [comment]
Confirmed to be resolved. Closing this issue.
