### ISSUE TITLE
Bug on a JS files shared by multiple packages when migrating

### ISSUE THREAD

**Issue by haochuan** [rehearsal-js/rehearsal-js#439]
Found a kinda critical issue during local test:

When `foo.js` is used by multiple packages (here "used" means that a single JS files appears in the migration file list from `migration-graph`), after the migration of the first package, `foo.js` would be converted to `foo.ts`, thus for migrations of other packages, it would throw an error that `foo.js` could not be found.

I don't have a good idea about how to deal with it at this moment though.

**Comment by haochuan** [comment]
No it's not in monorepo

**Comment by wondersloth** [comment]
We currently don't have support for a migration graph for a multi-package workspace.

This is an edge case for an ember-app with in-repo addons using a file in the root directory that's shared by the rootDir.

We currently don't define a directory boundary for an in-repo addon, as a result we don't resolve the path to some external package.

**Comment by wondersloth** [comment]
> > We currently don't have support for a migration graph for a multi-package workspace.
> 
> Is this true? Voyager uses workspaces

@chadhietala @lynchbomb 

Yes for plain JS (non-ember projects) we don't have package discovery logic. This needs to be decouples from the ember implementation and ported to `migration-graph-shared`.

The current logic  `package.json` discovery and edge creation only happens in the **@rehearsal/migration-graph-ember**.

FWIW
We never had workspace discovery support when this was extracted from voyager. 

There is some util code for detection and reading of workspace information on a package, but these APIs have not been used.

We need:
- [ ] `@rehearsal/migration-graph-shared` Add a method `discover` to `src/entitites/project-graph.ts`  to find packages in project similar to the `EmberAppProjectGraph`
- [ ] Add heuristics for filtering packages if a workspaces entry is found in the root `package.json`.
- [ ] Add tests that validate the correctness of a migration-graph for a plain JS project that is using **workspaces**.
- [ ] Add tests that evaluate **workspaces** and create **nodes and edges** from that data and add it to the graph.

**Comment by lynchbomb** [comment]
Should we close this with #515?

**Comment by wondersloth** [comment]
No, we still have the issue, I just need to add a boundary around a package now when we add it to the graph.

**Comment by wondersloth** [comment]
Problem
In a project where we have many packages. A package may have a import for a file outside of it’s workspace. This could typically be a shared config for build file.
<root>
├── package.json
├── some-util.js
└── packages/some-package/
  ├── package.json
  ├── index.js
  └── some-build.js // import '../../some-utils.js';

Solution
Ignore all files that resolve outside of the package from that package’s migration graph.
I wanted to talk about the compromise that has to be made when producing a graph, and why we must omit.

**Comment by chadhietala** [comment]
I'm reopening this because the original PR was reverted. #596 will close this issue.
