### ISSUE TITLE
migrate cli with ember app/addon

### ISSUE THREAD

**Issue by lynchbomb** [rehearsal-js/rehearsal-js#463]
In the use case of migrating a given Ember App or Addon from JS to TS. During the [Installing Dependencies](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/commands/migrate.ts#L169-L184) task, a conditional check for eg. `isEmber` we should also install all [pre-req's](https://typed-ember.gitbook.io/glint/using-glint/ember/installation#version-requirements) for Glint and Ember TypeScript (https://docs.ember-cli-typescript.com/installation).

Install Pre-Req Deps for Glint w/Ember Loose and Ember TypeScript:

```
yarn add --dev @glint/core @glint/template @glint/environment-ember-loose

ember install ember-cli-typescript@latest
```

^^^^ By doing above before executing [migrate](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/commands/migrate.ts#L220) the quality of type inference will be significantly better.

**Comment by lynchbomb** [comment]
We are going to implement this via "rehearsal-config.json" and expose an optional validator function hook. That way we can keep framework specific code as a plugin vs core feature:

https://github.com/rehearsal-js/rehearsal-js/pull/477#issuecomment-1338130078

**Comment by haochuan** [comment]
This is handled and completed internally via `rehearsal-config.json`
