### ISSUE TITLE
bug: handle migrate / upgrade re-run

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#480]
Testing globally installed `migrate ` on some repo and it failed at the second step because of global node version is not correct (14 vs 16)... 

```
✔ Initialization Completed! Running migration on repo.
✖ Command failed with exit code 1: /.../.volta/tools/image/yarn/1.22.10/bin/yarn add -D typescript --ignore-scripts
  error @docusaurus/core@2.0.1: The engine "node" is incompatible with this module. Expected version ">=16.14". Got "14.15.4"
  error Found incompatible module.
```

after I updated the global node and run migrate the second time it failed with:

```
✖ Cannot find module '/repo/index.js'
  Require stack: ...
```

We need to handle re-run cases somehow... either clean up changes (git reset), log states and skip some of them on re-run or somehow else.

**Comment by haochuan** [comment]
Done in #520
