### ISSUE TITLE
tsconfig error when running 'tsc'

### ISSUE THREAD

**Issue by brendaHuang** [rehearsal-js/rehearsal-js#490]
Two errors when running `yarn tsc`, which is step 5 for command `rehearsal migrate`: 

`error TS18003: No inputs were found in config file '/Users/brehuang/dev/eslint-plugin-pemberly/tsconfig.json'. `
`error TS5069: Option 'emitDeclarationOnly' cannot be specified without specifying option 'declaration' or option 'composite'.`

**Comment by lynchbomb** [comment]
@brendaHuang I believe we've removed running `tsc` within rehearsal migrate cli. if you grab the latest master and re-run that should be resolved?

**Comment by brendaHuang** [comment]
@lynchbomb Correct. Not seeing this error in the latest branch of rehearsal.
