### ISSUE TITLE
Explicit `any` usage should be reported

### ISSUE THREAD

**Issue by chadhietala** [rehearsal-js/rehearsal-js#508]
Right now when the codefixes run they emit `any` which we want people to remove. Typically we would report this usage via a lint rule since TypeScript allows the explicit usage of `any` even in `strict` mode. 

We need to figure out the best way of emitting this usage into the report. Some options:

1. Custom codefix
2. Use Eslint and somehow convert the Eslint report into a sarif entry (Checkup might be a good thing to look at)

**Comment by lynchbomb** [comment]
We should just NOT explicitly apply a CodeAction with `any` types. If we cannot infer the type we should not apply anything for this CodeAction.

**Comment by egorio** [comment]
Currently, CodeAction can add a few types at once, so it's not very useful and easy to filter out those CodeFixes.
After the fix with `any` types applied, the next step the hint comment will be added for any.

So we can change hint with better explanation and remove @ts-ignore / @ts-expect-error to keep error to be triggered.
