### ISSUE TITLE
feat(migration-graph): add workspace support for plain JS libraries

### ISSUE THREAD

**Issue by wondersloth** [rehearsal-js/rehearsal-js#514]
Reported and reference in issue #439 

- [x] `@rehearsal/migration-graph-shared` Add a method `discover` to `src/entitites/project-graph.ts`  to find packages in project similar to the `EmberAppProjectGraph`
- [x] Add heuristics for filtering packages if a workspaces entry is found in the root `package.json`.
- [x] Add tests that validate the correctness of a migration-graph for a plain JS project that is using **workspaces**.
- [x] Add tests that evaluate **workspaces** and create **nodes and edges** from that data and add it to the graph.

**Comment by chadhietala** [comment]
@wondersloth did #515 close this?

**Comment by aviheidir** [comment]
Confirm with @wondersloth this is fix
