### ISSUE TITLE
CSS files in module graph

### ISSUE THREAD

**Issue by chadhietala** [rehearsal-js/rehearsal-js#532]
Steps to reproduce:

1. `mint clone ember-cli-pemberly-m3`
2. `rehearsal migrate`
3. Notice that it tries to convert `/docs/src/pages/index.module.css to /docs/src/pages/index.module.ts`

**Comment by egorio** [comment]
![image](https://user-images.githubusercontent.com/1502496/208209045-f9af0a4f-62f4-425e-a209-dd9e02a09905.png)

**Comment by wondersloth** [comment]
```javascript
import styles from './index.module.css';
```

Causes the issue.
