### ISSUE TITLE
CodeFixes ordering

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#544]
Sometimes TS returns more than one CodeFix for provided error code.
We currently choose the first one, but we may choose to use the other solution.

I can found that 2 CodeFixes have more than one option:

![image](https://user-images.githubusercontent.com/1502496/208188250-554f68de-6d26-4f44-8545-9d5cb8723ac7.png)

I'm not sure if it's possible to get more than one choice for other issues.

I've experimented with the ordering of the code fixes, but with no luck because of missing `fixIds` in the results (see `undefined` in the screenshot). So, we might want to implement specific cases for those 2 codefixes: 

![image](https://user-images.githubusercontent.com/1502496/208189128-b21e6645-2130-4c78-8e7d-366f7e38cdfd.png)

The code I've used to debug:

![image](https://user-images.githubusercontent.com/1502496/208188764-751b05dc-8afe-4db2-bec2-87834e2ffe8b.png)

**Comment by chadhietala** [comment]
This is why interactive mode is really important 😄 . Any time where we can't reasonably pick between N options we should just ask the user and present the options.

For this case I was thinking we can actually create N temp copies of the text and apply the change. Once we do that we present it to the developer and ask them which fix they would like to apply to the real code.

For non-interactive mode I think all we can do is try and figure out some runtime heuristic at best or continue to take the first option. 

/cc @haochuan
