### ISSUE TITLE
No Files Found For Files In Root

### ISSUE THREAD

**Issue by chadhietala** [rehearsal-js/rehearsal-js#567]
Steps to reproduce:

1. mint clone upload-manager
2. `rehearsal migrate`
3. See that it finds no files

I believe the fix is that [`includePatterns`](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/migration-graph-shared/src/entities/package.ts#L77) here needs to have `main` and potentially export maps to find the entry point.

**Comment by wondersloth** [comment]
This has been fixed by #575

**Comment by chadhietala** [comment]
I'm reopening this because the PRs still need to be merged. #595 will close this ticket.
