### ISSUE TITLE
Make rehearsal results less noisy by applying less (approved) codefixes

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#591]
Create a list of "approved to apply" codefixes.

Can be done through options as described below:

Opposite, an engineer can decide to fix errors one by one across the project. For example, fix all 2353 errors only, create PR, them fix 2345 and create PR, etc. In this case, we can add a param to filter errors like `onlyErrors=2353,2345`.

To achieve this we need to [make plugins configurable](https://github.com/rehearsal-js/rehearsal-js/issues/314) 

Make sure errors related to https://github.com/rehearsal-js/rehearsal-js/issues/632 and https://github.com/rehearsal-js/rehearsal-js/issues/633 are fixed :)

**Comment by lynchbomb** [comment]
For folks with very close context around rehearsal and the typescript diagnostic codes I think this would be helpful. However the remaining ~99% - I dont think this is an API we should expose. 

Instead we should have an abstraction layer from this implementation via curated groups of diagnostics.

**Comment by lynchbomb** [comment]
We should prioritize #593 (_abstraction layer via curated groups of diagnostics_) over this issue and move this to the backlog and implemented if needed based on consumer feedback.
