### ISSUE TITLE
CLI command to rebuild Sarif "TODO list" based on `@rehearsal` comments in the file.

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#592]
As we already know there is an issue with line numbers in a Sarif report.

But even if lines are correct in the Sarif they can become invalid once an engineer fixes the error and will remove the `@ts-expect-error` comment or just modify the code manually.

The idea is to create a tool to quickly refresh (not rebuild with re-running compilation) "TODO" errors in the report and update lines for the rest, during the time an engineer works on `@ts-expect-error` cleaning. 

--

We can create CLI commands to rebuild the Sarif report (or its TODO part) based on all `@rehearsal` comments in all projects or in a particular file.

The command has to search for `@rehearsal` in the comments and updated the Sarif file with actual comments and line numbers.

We can also build this as an IDE plugin to rebuild Sarif once a file is modified.

**Comment by brendaHuang** [comment]
See #438

**Comment by lynchbomb** [comment]
Closing this as duplicate to. This issue is linked.
