### ISSUE TITLE
"fix" CLI flag to specify which curated set of diagnostics to run

### ISSUE THREAD

**Issue by lynchbomb** [rehearsal-js/rehearsal-js#593]
To achieve this we need to https://github.com/rehearsal-js/rehearsal-js/issues/314

Right now for the CLI migrate command we are running transforms against the kitchen sink of diagnostics after a curated set of [priority order diagnostics](https://github.com/rehearsal-js/rehearsal-js/blob/1d4170567611bbc78746bd59affe0e4200ccde2a/packages/plugins/src/plugins/diagnostic-fix.plugin.ts#L18-L29) 

In order for us to determine the value add of running ONLY the curated set vs the curated + kitchen sink we should expose a CLI flag eg. `rehearsal migrate --infer=minimal`.

Not sure specifically what we should call this; more so we need something like this.

**Comment by egorio** [comment]
We can do #591 and then we can implement `--infer=minimal` to compare sets of fixes.

**Comment by egorio** [comment]
@lynchbomb I'm going to do "minimal" (safe to applu codefixes) by default and `--infer=all` will be used instead.
