### ISSUE TITLE
--dry-run option for migrate CLI

### ISSUE THREAD

**Issue by haochuan** [rehearsal-js/rehearsal-js#601]
Adding a `--dry-run` option in `rehearsal migrate` would be useful for dev and testing things out.

**Comment by wondersloth** [comment]
`rehearsal migrate --dry-run`

Should print out a list of all the files that will be attempted to migrate. 

This way a user can verify if that the target files are correct and not including directories they wish to ignore.

This will be useful when we add expose a rehearsal config to users to customize which files or directories to include/exlucde.
