### ISSUE TITLE
[Epic] Integrate Glint Language Server For Migrating Ember Applications

### ISSUE THREAD

**Issue by chadhietala** [rehearsal-js/rehearsal-js#604]
[Glint](https://github.com/typed-ember/glint) is a superset of the TS language server that brings type checking to Ember/Glimmer templates. It does so by transforming HBS files to TS code, typechecking that and then mapping the ranges of those errors back into ranges in source code.

To fully type check properly migrate Ember applications we need to be able to use this language server to do the typechecking and codefixes for Ember applications.

The work that needs to happen here is:

- [x] Land https://github.com/typed-ember/glint/pull/499
- [x] #463 
- [x] #718 
- [ ] #722

**Comment by brendaHuang** [comment]
Bullet point 2 and bullet point 3 are overlapping with #463, so what's left of this ticket is bullet point 4.

**Comment by haochuan** [comment]
I've update the description and break down task 2 and 3 into different tickets (assigned to myself)
