### ISSUE TITLE
processing js files in docs/ directory

### ISSUE THREAD

**Issue by brendaHuang** [rehearsal-js/rehearsal-js#605]
Noticed we are not processing docs/src/pages/index.js in `ember-cli-pemberly-m3`. Question to be considered: Should we consider migrating `docs/` directory? 

Or the issue can be resolved by #602

**Comment by wondersloth** [comment]
Discussed with @brendaHuang over slack.

I think by default we should ignore a docs directory as that's typically code unrelated to the function of the package, and will require understanding what docs tools are being used and if they can be written with ts.

I think we should ignore the directory by default, and allow for inclusion of the directory at the discretion of the user (migrator) by adding it to their config in #602.
