### ISSUE TITLE
`.gjs` support in migration graph

### ISSUE THREAD

**Issue by chadhietala** [rehearsal-js/rehearsal-js#606]
Ember applications support a `.gjs` file extension. These files are effectively JS files with the exception in that they allow `<template>...</template>` tags within the file for declaring the template for a component. Components must but imported into the file explicitly and are called in `<template/>`s.

[Example](https://github.com/ember-template-imports/ember-template-imports/blob/master/tests/dummy/app/components/gjs-test.gjs)

These files need to be crawled and stitched into the module graph so that we can convert then from `.gjs` to `.gts` files with types.

We should be be able to use [`@glimmer/babel-preset`](https://github.com/glimmerjs/glimmer.js/tree/master/packages/%40glimmer/babel-preset) to parse the file and then start following the import declarations. Or we could try just using a [lexer](https://github.com/guybedford/es-module-lexer) that assumes the input is valid to get get the imports.

**Comment by wondersloth** [comment]
@chadhietala 

> We should be be able to use [@glimmer/babel-preset](https://github.com/glimmerjs/glimmer.js/tree/master/packages/%40glimmer/babel-preset) to parse the file and then start following the import declarations. Or we could try just using a [lexer](https://github.com/guybedford/es-module-lexer) that assumes the input is valid to get get the imports.

If given a source like:
```
import Component from '@glimmer/component';

const divide = () => 4 / 2;

const First = <template>Hello</template>

class Second extends Component {
  <template>world</template>
}

<template>
  <First/>, <Second/>!
</template>
```

From what I can tell `@glimmer/babel-preset` only does manipulation on `hbs()` calls to produce the correct transformations.

We need to use https://github.com/ember-template-imports/ember-template-imports to be able to parse a source file above.
