### ISSUE TITLE
Docs: Describe a few migration workflows

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#607]
I think it's good to answer this question in advance. 
Even if we will have docs on how to use migrate (params) it's good to have some common workflows described.

For example: 

- run migrate on directory/file /errors etc.
- create missing type definitions
- run migrate again 

or 

- run migrate on directory/file/errors etc.
- add/fix JSDoc
- run migrate again

**Comment by lynchbomb** [comment]
duplicate
