### ISSUE TITLE
Migrate CLI doesn't respect yarn/npm version with volta

### ISSUE THREAD

**Issue by haochuan** [rehearsal-js/rehearsal-js#644]
During rehearsal migrate initialization task, if a machine uses `volta` to control the package manager's version, [getModuleManagerInstaller](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/utils.ts#L237) would always user the default global version, instead of using the one specified in the project.

For example, if `yarn` in `package.json` has been pinned to version 3:
```
 "volta": {
  34   │     "node": "16.15.0",
  35   │     "yarn": "3.2.1"
  36   │   }
```

Inside the project:
```
❯ which yarn
~/.volta/bin/yarn

❯ yarn -v
3.2.1
```

However, in [getModuleManagerInstaller](https://github.com/rehearsal-js/rehearsal-js/blob/master/packages/cli/src/utils.ts#L237), `const bin = which.sync(manager);` would be the global one `~/.volta/tools/image/yarn/1.22.10/bin/yarn` instead of `~/.volta/bin/yarn`. This would cause a lot of potential issues for the mismatched package manager's version.

**Comment by egorio** [comment]
Seems related and will be fixed as well https://github.com/rehearsal-js/rehearsal-js/issues/429

**Comment by haochuan** [comment]
In any place
