### ISSUE TITLE
Implement Instant feedback for invalid basePath cli option

### ISSUE THREAD

**Issue by brendaHuang** [rehearsal-js/rehearsal-js#660]
Currently if we pass in an invalid basePath cli option with '-p' or '--basePath', we will get an error from git ('`Cannot use simple-git on a directory that does not exist`') when git tries to check if there's uncommitted changes. 

The ideal behavior is we give instant feedback if invalid basePath is passed, so that the error is easier to understand and cli is more robust.

**Comment by lynchbomb** [comment]
This has been removed from cli
