### ISSUE TITLE
Skip Steps On Sequential Runs

### ISSUE THREAD

**Issue by chadhietala** [rehearsal-js/rehearsal-js#692]
I noticed that when we run rehearsal multiple times on a project e.g. using `-e` to migrate certain parts of a repo, we still go through installing dependencies, creating tsconfig, and creating eslint config. I think we can detect these things in initialization and skip over them if we have done them already.

**Comment by egorio** [comment]
Oh. We just discussed this with @wondersloth :)
We can also skip checking if the repo is dirty in this case.
