### ISSUE TITLE
Integrate Glint language service

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#722]
Part of https://github.com/rehearsal-js/rehearsal-js/issues/604

Refactor and adapt all the places where are typechecking or modifying code to go through an abstraction that adapts calls to the Glint and TS language server. It may be necessary to use Glint's [transformmanager](https://github.com/typed-ember/glint/blob/main/packages/core/src/index.ts#L35) to properly modify code.

This can be solved through: https://github.com/rehearsal-js/rehearsal-js/issues/689

**Comment by lynchbomb** [comment]
@egorio and @cafreeman I think this can be closed now?
