### ISSUE TITLE
New command (3rd) `rehearsal retry`

### ISSUE THREAD

**Issue by lynchbomb** [rehearsal-js/rehearsal-js#725]
We want to cover the instance of an app which is already migrated to typescript, however still has TODO's. This new command has slight overlap with `upgrade` and `--regen`. The command should take in .ts files, remove the @ts-expect-error messages and re-run the CodeAction plugins. 

Likely we dont need any flags for this command. It should "autofix" and "regen" every time. We already have all the "guts" for this command. Its more just packaging internals and exposing this new API.

**Comment by egorio** [comment]
We need to rethink the scope of commands. They overlap each other in some cases :)

**Comment by lynchbomb** [comment]
At the moment we really just need a quick implementation for `rehearsal migrate --init` so we can start scaffolding libraries. A lot of this is UX improvement, which I'd like to get more feedback from early adopters on before we make this refactor; and likely we will need alias commands.

**Comment by lynchbomb** [comment]
WRT the proposed above:

- `rehearsal init` would cover both `migrate` and `upgrade`?
- `--force` is confusing to me. why not just do the thing without forcing
- `rehearsal report` this is also confusing for me, since we already have report flags in upgrade and migrate.

**Comment by egorio** [comment]
- `rehearsal init` - it's independent of migrate and upgrade, can be used with both commands both
- `command can be run without `--force`, force is just an option to rerun fixes on all files (solution for this task)...
- `rehearsal report`- won't apply any fixes, report existing diagnostic issues, and update `-report.*` files (--regen)
- `rehearsal upgrade --configs` - agree :), in general, init can be one step of `migrate`, the same way as `report`.

**Comment by egorio** [comment]
Let's rename it to `migrate fix`
