### ISSUE TITLE
Better description for `basePath` and `entrypoint`

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#752]
It's not clear what these options are used for from the current description.

```
-p, --basePath <project base path>                         base directory of your project (default: "/Users/everbits/Sites")
-e, --entrypoint <entrypoint>                              entrypoint filepath of your project (default: "")
```

Need to provide a better description of options to make sure users understand how to use then

**Comment by wondersloth** [comment]
Context relative to internal early adopters

* Early adopters are unsure where to run **rehearsal migrate** in a monorepo project.
* Some are invoking from root or within a package in the project, and not the root.
* Action Item: The workflow that an _early adopter_ should be clarified.
