### ISSUE TITLE
Docs: Workflow Recommendation, migrate a single package inside of an monorepo.

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#753]
Users are confused by a large number of changes made by Rehearsal:

- [ ] Document workflow to migrate monorepos by single package, directory, or even file level.
- [ ] Document how to do a leaf-to-root file-level migration.
- [ ] We also can consider creating a command like `rehearsal graph` to help people to make a decision on when to start migration if there are a lot of files in the app.

**Comment by lynchbomb** [comment]
@wondersloth for this issue will you handle:

```
- Document workflow to migrate monorepos by single package, directory, or even file level.
- Document how to do a leaf-to-root file-level migration.
```
