### ISSUE TITLE
SonarQube Reporting Documentation

### ISSUE THREAD

**Issue by lynchbomb** [rehearsal-js/rehearsal-js#756]
This is a reminder issue to be sure all documentation is complete and value add of leveraging SonarQube

**Comment by aviheidir** [comment]
@brendaHuang -- here's the outline of the Rehearsal reporting I was thinking of:

- Introduction
- Rehearsal report in SonarQube: What information can a user find here? Who are the target audiences? eng, manager/leadership, infra eng? What does each of these target audiences get?
- Tracking migration progress: How do users find and read the migration progress report
- Sequential Runs: What is this? Why is this matter to the user?
- Generating Rehearsal Report: CLI options and report formats

**Comment by aviheidir** [comment]
Link to the draft: https://docs.google.com/document/d/1E_6L0MYFXdCUicbC7q_gXGeOf_TMGsPu-7RrEb4UC0A/edit#

**Comment by brendaHuang** [comment]
Documentation published in wiki, announced in early adopter channel.
