### ISSUE TITLE
Seeding tags for sonarqube

### ISSUE THREAD

**Issue by brendaHuang** [rehearsal-js/rehearsal-js#773]
We need to seed tags for sonarqube tagging: scrapping typescript-diagnostics from the typescript github site.

**Comment by brendaHuang** [comment]
Ticket suspended/cancelled.

**Comment by wondersloth** [comment]
Reason for backlogging. Feature for tagging has been paused due to internal concerns.

**Comment by brendaHuang** [comment]
MP was created to tag Sonarqube by project before ticket was suspended.
