### ISSUE TITLE
migration-graph: pass project level excludes to all packages in a project.

### ISSUE THREAD

**Issue by wondersloth** [rehearsal-js/rehearsal-js#787]
### Problem

- In `rehearsal-config.json` the exclude property  only a apply to the root package in a project (EmberApp, EmberAddon or Library).
- Unable to ignore a directory within a package in workspace.

### Use Case

- [ ] As a user, when they want to exclude some file extension that's used in my imports like `.css`, `.graphql`, `.json` the config should have a option for excluding just that.
- [ ] As a user, when they want to to exclude a directory from within a package, there should be a option for this in the config. (e.g. `packages/some-package/test` when running `rehearsal migrate` fro the root, should omit that portion of the graph from the output or graph).

### Implementation Details
We can pass these into dependency-cruiser with the following regex format:
```
\\.css$
\\.graphql$
\\.json$
```
- [ ] Should not pass complexity for regexs to the user. Maybe just have the extension as a suffix.
- [ ] Create an API in rehearsal-config that extends the excludes property to be an object:
       ```
       exclude = string[] | { paths: string[], extensions: string[] }
       ```
      We can construct the regex from this array of `.css`
- [ ] Document how to pass file extensions excludes.

**Comment by lynchbomb** [comment]
Fixed with —ignore flag
