### ISSUE TITLE
Internal CLI config failing on missing typescript dependency

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#799]
There is an error when the user runs config CLI without typescript preinstalled:

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'typescript'
Require stack:
- /***/rehearsal-cli-config/node_modules/@rehearsal/utils/dist/src/tsc-utils.js
- /***/rehearsal-cli-config/node_modules/@rehearsal/utils/dist/src/index.js
- /***/rehearsal-cli-config/dist/commands/migrateConfig.js
- /***/rehearsal-cli-config/dist/index.js
- /***/rehearsal-cli-config/bin/rehearsal-cli-config.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
```

This is happening because non of `rehearsal-cli-config` and `@rehearsal/utils` have `typescript` in deps while `@rehearsal/utils`` require it and has it in `peerDeps` only.

But they functionality used by `rehearsal-cli-config` from `@rehearsal/utils` don't need typescript at all.

Solution is to just drop dependency on `@rehearsal/utils` :)

**Comment by lynchbomb** [comment]
Issue resolved internally
