### ISSUE TITLE
Need to add --ignore-scripts in internal config

### ISSUE THREAD

**Issue by brendaHuang** [rehearsal-js/rehearsal-js#802]
**Error:** 
brehuang-mn1:process-manager-js brehuang$ rehearsal migrate -u rehearsal-config.json
info: @rehearsal/migrate 1.0.10-beta
✔ Validate project
✔ Initialize
✔ Install dependencies
✖ Command failed with exit code 1: rehearsal-cli-config migrate-config ts-setup node16 --buil…
If you do not have a build step you can use use TypeScript’s “tsc” command line tool to gen…
/Users/brehuang/.volta/tools/image/packages/@linkedin/rehearsal-cli-config/lib/node_modules…
error = new Error(message);
^
Error: Command failed with exit code 126: volta run yarn add -D @linkedin/ts-bases
error Command failed with exit code 2.
For full error output, see attached file. 
[error-when-running-rehearsal.txt](https://github.com/rehearsal-js/rehearsal-js/files/10885017/error-when-running-rehearsal.txt)

**Steps to reproduce:** 
```
git clone org-70@linkedin.ghe.com:multiproduct/process-manager-js.git
cd process-manager-js 

volta install @linkedin/rehearsal-cli-config
rehearsal-cli-config migrate-config init

volta install @rehearsal/cli
rehearsal migrate -u rehearsal-config.json
```
**Solution:**
per @haochuan: Seems `"prepare": "tsc && esbuild --bundle dist/index.js --platform=node --outfile=dist/index.cjs && yarn prepare:test-support"` is failing. And seems prepare was triggered via yarn install we need to add `--ignore-scripts` in our internal config when doing install with `yarn@1`, as same as what we did in OSS

**Comment by haochuan** [comment]
This is completed via internal config (just adding required deps into `rehearsal-config.json`, remove all installation action, and let `rehearsal` handle it)
