### ISSUE TITLE
lint config files are being changed from js to ts

### ISSUE THREAD

**Issue by brendaHuang** [rehearsal-js/rehearsal-js#813]
In migrating hue libraries, for example, hue-web-button, lint config files, such as .eslintrc.js, .rehearsal-eslintrc.js, and .template-lint.js are being converted to ts files. TS errors and lint errors are being produced for these files, and lint errors for other source files become inaccurate because of this.

**Comment by lynchbomb** [comment]
@wondersloth ^^^ can you take a look
