### ISSUE TITLE
Unable to find binary path to tsc

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#821]
Issue `Unable to find binary path to tsc` happens when running rehearsal migrate from within an addon with `rehearsal-config.json` initialized in the root (on `voy***-web` for context)

**Comment by lynchbomb** [comment]
I thought this was already resolved? Is this confirmed with the latest build?

**Comment by lynchbomb** [comment]
@egorio any updates on this? Can this be closed?

**Comment by lynchbomb** [comment]
Closing this as we cannot replicate. Reopen if we do.
