### ISSUE TITLE
feat(cli): rehearsal-config add option for ember service resolution map

### ISSUE THREAD

**Issue by wondersloth** [rehearsal-js/rehearsal-js#823]
To simplify service discovery or mapping, and bypass service package resolution errors. 

Add a config to `rehearsal-config.json` such that we can tell the ember project what some service resolutions should point to.

```json
{
  "$schema": "https://raw.githubusercontent.com/rehearsal-js/rehearsal-js/master/packages/cli/rehearsal-config-schema.json",
  "upgrade": {},
  "migrate": {
    "ember": {
      "serviceResolutions": {
        "lix": "@linkedin/ember-cli-pembelry-lix",
        "i18n": "@linkedin/ember-cli-pembelry-i18n",
      }
    },
  }
}
```

This could support support services types more as we can attach this meta data to the file graph node and expose it to migrate.

This API for lookup and tests exist in [`EmberAppPackageGraph`](https://github.com/rehearsal-js/rehearsal-js/blob/56e972cf90cff858fd28d249b04f84ba1e5e4440/packages/migration-graph-ember/src/entities/ember-app-package-graph.ts#L131)

**Comment by lynchbomb** [comment]
@wondersloth i like this idea. We should be able to seed the most common of these based on dependencies.
