### ISSUE TITLE
feat: provide a complete package graph for interactive mode

### ISSUE THREAD

**Issue by wondersloth** [rehearsal-js/rehearsal-js#841]
### Problem
We are using `discoverEmberPackages()` for all usages in interactive mode. This is not correct for a couple reasons:
- Obviously because not all usages of **interactive** mode should be for an ember project. We have regular JS workspaces to support.
- Secondly, to complete an ember graph of package dependencies we **must parse all source files** to get all inferred service dependencies from each file in an ember package, and thus the **complete** graph can change after those inferred service dependencies have been discovered

We need to drop this API and have a base implementation to get packages  to get this information from a graph of packages for any sort of workspace-like project. 

### Challenges
- We want to do the minimal amount of work necessary when parsing a graph.

### Recommendations

**Always parse the entire project**
We can parse the entire project, and store that data for future reference (serialize off to disk). Then once a package is selected we can show the package and it's upstream dependents.

#### Cheap parsed graph 
We can easily find all packages in a project. We should surface this quick list of packages because we can grab all `package.json`s in a project, but to create an accurate list of packages with a close but not accurate order.

This could use package.json data but not parse files.
*Pros*
It's fast and in large projects (voyager) we don't want to parse all files all the time.

*Cons*
I don't think we should provide any inaccurate ordering. This would weaken the brand or purpose of this tool.

#### **Don't** surface a package graph in interactive mode.
Not great if you want to find the leaf package of project, but if we have an API for someone to migrate a single package, we can infer the upstream packages very accurately. 

Not a complete solution alternative, but addresses the use case of "I want to migrate some-package, let me find everything upstream that has to be migrated.".

**Comment by lynchbomb** [comment]
@wondersloth lets update/include as part of #957
