### ISSUE TITLE
feat: refactor ProjectGraph to have similar package inferrence like in EmberAppProjectGraph

### ISSUE THREAD

**Issue by wondersloth** [rehearsal-js/rehearsal-js#860]
### What
`ProjectGraph.discoverByEntrypoint()` needs to be improved to infer the closest package like in `EmberAppProjectGraph` solution shown in #838

- Currently is uses the root package. 
- What it should do is find up for the nearest package.

### Why?
- Fixes: #825 for plain js workspaces
- Potential to help improve package meta data that can improve graph file resolution.

### When?
Our internal projects would not benefit from this feature, this is why it should be a backlog item.

**Comment by lynchbomb** [comment]
@wondersloth @chadhietala is this related to #964

**Comment by wondersloth** [comment]
Yes. Just a non-ember version. That entry point work should be refactored to the base class.
