### ISSUE TITLE
Running rehearsal-cli-config on ember project gets error 'glint configuration' not found

### ISSUE THREAD

**Issue by brendaHuang-2023** [rehearsal-js/rehearsal-js#871]
Steps to reproduce:

- install internal config
- run `rehearsal-cli-config migrate-config init`
- run local build of master branch on project with rehearsal-config.json
- see screenshot
<img width="583" alt="Screenshot 2023-03-21 at 5 17 58 PM" src="https://user-images.githubusercontent.com/128413665/226770239-dbba7910-e8da-4cf5-af52-2c62b312b664.png">

**Comment by haochuan** [comment]
Handled in internal tooling, close.
