### ISSUE TITLE
Improve performance of find_Node functions:

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#890]
PERFORMANCE IMPROVEMENT

We have few functions to search for a particular node. 

The most used is `findNodeAtPosition` which is used for every diagnostic to find the related node.

The current approach the function is implemented is to walk through a whole file from top to bottom (all AST tree nodes), but we can just technically skip all nodes that don't include the target node inside (getStart and getEnd).

The same happens with `findTheFirstParentNodeInTheLine` and `findNodeEndsAtPosition`.

**Comment by lynchbomb** [comment]
fixed in #912
