### ISSUE TITLE
Unexpected output from glint -fix and -check plugins

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#900]
I added the next example to `*.gjs` test file:

```
/**
 * JSDoc
 *
 * @param {number} a 
 * @param {UnavailableType} b 
 *
 * @return {void}
 */
export function think(a, b) {
  return console.log(a, b);
}
``` 
and got:

```
/**
 * JSDoc
 *
 * @param {number} a 
 * @param {UnavailableType} b 
 *
 * @return {void}
 */
{{! @glint-expect-error @rehearsal TODO TS80004: JSDoc types may be moved to TypeScript types. }}
{{! @glint-expect-error @rehearsal TODO TS7006: Parameter 'a' implicitly has an 'any' type. }}
{{! @glint-expect-error @rehearsal TODO TS7006: Parameter 'b' implicitly has an 'any' type. }}
export function think(a, b) {
  return console.log(a, b);
}
``` 

in the example above the expected output is `a: number, b: UnavailableType` and comment about `UnavailableType` type.

There are a few problems to fix:
- ~Seems Glint's getCodeFixes doesn't return TS standard fixes... and defiantly not rehearsal ones. We need to make sure all available code fixes are used.~
- Multiple comments are added to the same error line... but only one comment is expected

**Comment by lynchbomb** [comment]
@cafreeman ^^^
