### ISSUE TITLE
Bug: `rehearsal-cli-config` should always add glint configuration 

### ISSUE THREAD

**Issue by wondersloth** [rehearsal-js/rehearsal-js#920]
## Summary
- Currently in `--ci` the `rehearsal-cli-config` skips the `tsconfig.json` modification where `"glint"` is added.
- This is because the `shouldRunTsConfigTask` returns  `false`.
  - In `shouldRunTsConfigTask` the task checks `tsconfig.json` [to **NOT** have `compilerOptions.strict` to `true`](https://github.com/rehearsal-js/rehearsal-js/blob/892b22b597687eee17237c4faed888fb8dcf8bef/packages/cli/src/commands/migrate/tasks/config-ts.ts#L24)
- All LinkedIn MPs use `ts-bases` where it's defined and when `tsconfig` is parsed it will have that value set to `true`.

## Steps to reproduce:
- learning-web has a `tsconfig.json`
- When `tsconfig.json` [shouldRunTsConfigTask checks to see if compilerOptions.strict == true](https://github.com/rehearsal-js/rehearsal-js/blob/892b22b597687eee17237c4faed888fb8dcf8bef/packages/cli/src/commands/migrate/tasks/config-ts.ts#L24)

## Recommendation
- Recommend glint modification from rehearsal-cli-config to always run and apply against `tsconfig.json`

**Comment by brendaHuang-2023** [comment]
Seeing this error: `Unable to find Glint configuration for /Users/brehuang/dev/ember-restli`
