### ISSUE TITLE
Bug: config files should not be converted to ts

### ISSUE THREAD

**Issue by brendaHuang-2023** [rehearsal-js/rehearsal-js#923]
jest.config.js was converted to jest.config.ts for core-web-i18n-preprocessors
docusaurus.config.js was converted to docusaurus.config.ts for core-web-api-metadata-tools

**Comment by lynchbomb** [comment]
@brendaHuang-2023 were these files in the project root or within a source files directory?

**Comment by brendaHuang-2023** [comment]
@lynchbomb jest.config.js is in the root directory of `core-web-i18n-preprocessors`. 

docusaurus.config.js is in the docusaurus directory of `core-web-api-metadata-tools`.
