### ISSUE TITLE
Docs: Update README with build changes (main, files, types)

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#927]
Package.json has several directives that need to be updated/verified after the project is migrated from JS to TS.

A few of them are `main`, `files`, and `types`.

### main
We need to make sure (as the one of migration steps):
- if the existing main is pointed to a file we renamed => we need to point it to compiled file in dist
- if the main file is not modified by us, but has import/require statements pointing to files we modified => need to update those imports.
- if we can't update handle this => just notify the developer to step up and check the main file.

### files
we need to make sure files include `dist` to be a part of the released package.

### types
we can add `types` pointed to the d.ts of the main file by default.

**Comment by lynchbomb** [comment]
This should be handled outside of rehearsal with the building configuration eg. babel/rollup

We should however document this is a thing you’ll need to do after migration for the developers in rehearsals README

**Comment by lynchbomb** [comment]
DONE https://github.com/rehearsal-js/rehearsal-js#packagejson-directives
