### ISSUE TITLE
Convert exports to ES Module

### ISSUE THREAD

**Issue by egorio** [rehearsal-js/rehearsal-js#936]
Don't forget to revert [this one](https://github.com/rehearsal-js/rehearsal-js/pull/940/files)

We currently apply `requireInTs` transform to change `requre()` to `import` but this trigger errors that we trying to import not ES modules. 

There is a codefix called `convertToEsModule` but it's not triggered as expected. 

Need to find a way to enable this plugin or find work around issues comes with `requireInTs` fix.

![image](https://user-images.githubusercontent.com/1502496/230205670-8cd34c79-6a19-4faa-836c-cdd64eeb6cba.png)

**Comment by egorio** [comment]
Progress: https://github.com/rehearsal-js/rehearsal-js/tree/everbits/936

**Comment by lynchbomb** [comment]
^^^ lets disable this codefix for now

**Comment by egorio** [comment]
Disabling codefix: https://github.com/rehearsal-js/rehearsal-js/pull/940
