### ISSUE TITLE
Bug: migration stuck on IIFE

### ISSUE THREAD

**Issue by brendaHuang-2023** [rehearsal-js/rehearsal-js#949]
Migrate stuck on IIFE (Immediately Invoked Function Expression) while migrating pemberly-fastboot-server: pemberly-fastboot-server/__tests__/fixtures/app-with-error/assets/test-support.ts

Question to consider: 
Adding prerequisite before running `migrate`: no IIFE?

**Comment by lynchbomb** [comment]
@egorio will you take a look at this?

**Comment by egorio** [comment]
I'm getting

![image](https://user-images.githubusercontent.com/1502496/232938968-f807b3a7-da74-4d40-9672-888039685e70.png)

**Comment by egorio** [comment]
Code block causing the error:

```
(function() {

  const config = {
    modules: [],
    currentModule: {},
  };
  
  config.modules.push(config.currentModule);
}();

```
