### ISSUE TITLE
Bug: Fail to load plugin '@linkedin/typescript'

### ISSUE THREAD

**Issue by brendaHuang-2023** [rehearsal-js/rehearsal-js#953]
brehuang@brehuang-mn1 urn-utils % migrate
info:    @rehearsal/migrate 1.0.18-beta
warn:    You have uncommitted files in your repo. You might want to commit or stash them.
✔ Validate project
✔ Initialize
↓ Install dependencies [SKIPPED]
✔ Create tsconfig.json
↓ Create eslint config [SKIPPED]
✔ Add package scripts
✔ Analyze project
✖ Failed to load plugin '@linkedin/typescript' declared in '.eslintrc.js': Class extends value undefined is not a con…
  Referenced from: /Users/brehuang/dev/urn-utils/.eslintrc.js
error:   Failed to load plugin '@linkedin/typescript' declared in '.eslintrc.js': Class extends value undefined is not a constructor or null
Referenced from: /Users/brehuang/dev/urn-utils/.eslintrc.js
TypeError: Failed to load plugin '@linkedin/typescript' declared in '.eslintrc.js': Class extends value undefined is not a constructor or null
Referenced from: /Users/brehuang/dev/urn-utils/.eslintrc.js
    at Object.<anonymous> (/Users/brehuang/dev/urn-utils/node_modules/@typescript-eslint/utils/dist/ts-eslint/Linter.js:11:31)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/brehuang/dev/urn-utils/node_modules/@typescript-eslint/utils/dist/ts-eslint/index.js:20:14)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
(node:55743) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:55743) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:55743) Warning: Accessing non-existent property 'which' of module exports inside circular dependency

**Comment by lynchbomb** [comment]
This is odd. Can you share the .eslintrc file? Possibly malformed?

**Comment by brendaHuang-2023** [comment]
@lynchbomb Here's the .eslintrc.js

```
module.exports = {
  root: true,
  plugins: ['@linkedin/typescript'],
  extends: ['plugin:@linkedin/typescript/migration'],
  parser: '@typescript-eslint/parser',
  parserOptions: { tsconfigRootDir: __dirname },
};
```

.eslintrc.js seems to be correct. It's the product of running `rehearsal-cli-config migrate-config lint-setup node16`, which looks OK when I compare the code in internal config.

**Comment by brendaHuang-2023** [comment]
@lynchbomb 
It turns out the crash is caused by the existing outdated eslint in urn-utils. eslint@3.x is too old to support plugins. Rehearsal verifies the targeting project has eslint, but does not check eslint version.

**Comment by brendaHuang-2023** [comment]
Closing this issue as it's user's responsibility to update/install dependencies since we removed dependency installation from rehearsal.
